name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: ./hardware
      run: make
  test:
    runs-on: ubuntu-latest
    steps:
    - name: make test
      working-directory: ./hardware
      run: make test
