name: C++/Python Test

on:
  push:
    branches: [ main ] # メインブランチへのpush時
    paths:
      - 'hardware/**'
      - 'software/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ] # メインブランチへのPR時
    paths:
      - 'hardware/**'
      - 'software/**'
      - '.github/workflows/test.yml'

jobs:
  hw-test:
    name: Hardware Test (C++)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run C++ Test
        run: |
          cd hardware
          make hw-test

  sw-test:
    name: Software Test (Python Unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # - name: Install Python dependencies
      #   run: pip install pytest etc

      - name: Run Python Unit Tests (Placeholder)
        run: echo "No Python unit tests yet."

  test:
    name: Integration Test (Python + SO)
    runs-on: ubuntu-latest
    needs: hw-test # hw-testジョブの完了を待つ
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install numpy

      - name: Build C++ shared library
        run: |
          cd hardware
          make $(make -C hardware -sp | grep '^TARGET_SO :=' | cut -d' ' -f3) # MakefileからTARGET_SOを取得してビルド

      - name: Run Python Integration Test
        run: python3 software/run-test.py
