name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd hardware && make
    - name: make test
      run: cd hardware && make test
    - uses: actions/setup-python@v1
      with:
        python-version: 3.10.15
    - name: Python test
      run: python3 test.py
